---
- name: install dev config
  copy: src=php.ini dest=/etc/php5/cli/php.ini owner=root group=root mode=0755
- name: get phpunit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit
- name: make phpunit executable
  file: path=/usr/local/bin/phpunit mode=o+x state=file
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -d allow_url_fopen=On && sudo mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
