---
- name: install dev config
  copy: src=php.ini dest=/etc/php/7.0/cli/php.ini owner=root group=root mode=0755
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
