---
- name: install dev config
  copy: src=php.ini dest=/etc/php5/cli/php.ini owner=root group=root mode=0755
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
- name: ensure composer bin dir exists
  # https://getcomposer.org/doc/03-cli.md#composer-home
  # https://getcomposer.org/doc/06-config.md#bin-dir
  file: path=/home/{{ansible_ssh_user}}/.composer/vendor/bin owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0755 state=directory
- name: add composer bin dir to .profile
  lineinfile: create=yes state=present line=PATH=\"$HOME/.composer/vendor/bin:$PATH\" dest=/home/{{ansible_ssh_user}}/.profile
# execute all composer global ops without sudo
- name: install phpunit
  sudo: no
  shell: composer global require phpunit/phpunit creates=/home/{{ansible_ssh_user}}/.composer/vendor/bin/phpunit
