---
- name: install vim
  apt: name='vim' state=present
- name: create vim bundles directory
  become: false
  file: path=/home/{{ansible_ssh_user}}/.vim/bundle state=directory
- name: install vundle
  become: false
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/{{ansible_ssh_user}}/.vim/bundle/Vundle.vim
- name: install editorconfig core
  apt: name=editorconfig state=present
- name: install .vimrc
  become: false
  copy: src=.vimrc dest=/home/{{ansible_ssh_user}}/.vimrc owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0755
  notify: install vundle plugins
