---
- name: create php logs folder
  file: path=/var/log/php state=directory owner=root group=root mode=0777
- name: ensure php error log file exists
  file: path=/var/log/php/err.log state=touch owner=root group=root mode=0777
- name: install production config
  copy: src=php.ini dest=/etc/php5/fpm/php.ini owner=root group=root mode=0755
- name: ensure fpm error log file exists
  file: path=/var/log/php/fpm.log state=touch owner=root group=root mode=0777
- name: install fpm config
  copy: src=fpm.conf dest=/etc/php5/fpm/php-fpm.conf mode=755 owner=root group=root
- name: ensure fpm "www" pool access log file exists
  file: path=/var/log/php/www.log state=touch owner=root group=root mode=0777
- name: ensure fpm "www" pool slow log file exists
  file: path=/var/log/php/www.log.slow state=touch owner=root group=root mode=0777
- name: install fpm pool config
  template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf mode=755 owner=root group=root
