---
- name: add mongo apt key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927 state=absent
- name: add mongo apt repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu/ xenial/mongodb-org/3.2 multiverse' state=present
- name: install mongo shell
  apt: update_cache=yes name="mongodb-org-shell" state=present
