---
- name: add mongo apt key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present
- name: add mongo apt repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu/ trusty/mongodb-org/3.0 multiverse' state=present
- name: install mongo shell
  apt: update_cache=yes name="mongodb-org-shell" state=present
