---
- name: add ansible repo
  apt_repository: repo='ppa:ansible/ansible' state=present
- name: install ansible
  apt: update_cache=yes name='ansible' state=present
- name: install curl
  apt: name='curl' state=present
- name: install python pycurl module
  apt: name='python-pycurl' state=present
- name: install python psycopg2 module
  apt: name='python-psycopg2' state=present
