---
- name: add postgres apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
- name: add postgres apt repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
- name: update apt cache
  apt: update_cache=yes
