---
- name: add php repo
  apt_repository: repo='ppa:ondrej/php' state=present
- name: install php cli
  apt: update_cache=yes name=php7.0-cli state=present
- name: install zip ext
  apt: name=php7.0-zip state=present
- name: install mbstring ext
  apt: name=php7.0-mbstring state=present
